<a href='https://www.k2analytics.in'> <img src='https://k2analytics.co.in/wp-content/uploads/2020/03/Divi-K2-Logo.png' /></a>

***
# NUMPY
***
<font color = #318CE7 size = 3 >

> **What is NUMPY ?**

__NumPy (short for `Num`erical `Py`thon) is an open source Python library for doing scientific computing with Python.__

***

> `NumPy is the foundation of the python scientific stack`

<img src="images/numpy.png" title="NumPy Ecosystem" width = 400 height = 200>

<font>

[NUMPY REFERENCE](http://scipy-lectures.org/intro/numpy/index.html)

***

In [1]:
# importing numpy
import numpy as np

### Note: All values in numpy are of same data type

In [2]:
# 1d-array
my_list = ["10.8",2,1]
array1d = np.array(my_list)
array1d

array(['10.8', '2', '1'], dtype='<U11')

In [3]:
my_list

['10.8', 2, 1]

In [4]:
print(type(my_list), type(array1d))

<class 'list'> <class 'numpy.ndarray'>


### - **` Axes in arrays `**
***
<font color = #318CE7 size = 3 >
    
Axes are defined for arrays with more than one dimension.


***

<img src="images/axes_numpy.png" title="NumPy Axes" width = 500 height = 500>

***

<img src="images/arrays.png" title="NumPy Array" width = 500 height = 500>

***

</font>

In [5]:
my_sublist = [
    [1.5,2.5,3.5,4],
    [4.5,5.5,6.5,1],
    [7.5,8.5,9.5,6]
] # list of three by four list
my_sublist

[[1.5, 2.5, 3.5, 4], [4.5, 5.5, 6.5, 1], [7.5, 8.5, 9.5, 6]]

In [6]:
# if I cast the above list into an array : i get output as a 2d-array
array2d = np.array(my_sublist)
array2d

array([[1.5, 2.5, 3.5, 4. ],
       [4.5, 5.5, 6.5, 1. ],
       [7.5, 8.5, 9.5, 6. ]])

In [7]:
array2d.shape # m * n matrix

(3, 4)

In [8]:
array3d_image = np.array([
    
    [['R1', 'G1', 'B1'], ['R2', 'G2', 'B2']], 
    
    
    [[155, 209, 119], [156, 209, 125]]
])
array3d_image

array([[['R1', 'G1', 'B1'],
        ['R2', 'G2', 'B2']],

       [['155', '209', '119'],
        ['156', '209', '125']]], dtype='<U11')


### - **` Some Default Attributes `**
***
<font color = #318CE7 size = 3 >
    
> **The main data structure for multidimensional arrays in NumPy is the `ndarray class`.**

Attribute    :    Description <BR>

- `shape` : specifies the number of elements for each dimension of the array.
- `size` : total number elements in the array.
- `ndim` : Determines the dimension an array.
- `nbytes` : Number of bytes used to store the data.  
- `dtype` : Determines the datatype of elements stored in array.
    
***

</font>

***

In [9]:
# data type
print(array1d.dtype)
print(array2d.dtype)
print(array3d_image.dtype)

<U11
float64
<U11


In [10]:
# shape
print(array1d.shape) 
print(array2d.shape)
print(array3d_image.shape)

(3,)
(3, 4)
(2, 2, 3)


In [11]:
# number of dimensions
print(array1d.ndim)
print(array2d.ndim)
print(array3d_image.ndim)

1
2
3


In [12]:
# size
print(array1d.size)
print(array2d.size)
print(array3d_image.size)

3
12
12


In [13]:
# bytes occupied in memory
print(array1d.nbytes)
print(array2d.nbytes)
print(array3d_image.nbytes)

132
96
528



### - **` Reshape an array `**
***
<font color = #318CE7 size = 3 >
    
 > The `reshape()` method modifies existing shape but original array remains unchanged.
 
</font>

***

In [14]:
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_array_1 = the_array.reshape(2, 4)
print(reshaped_array_1)
 
print("-" * 20)

reshaped_array_2 = the_array.reshape(4, 2)
print(reshaped_array_2)
 

[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]



### - **` Resize an array `**
***
<font color = #318CE7 size = 3 >
    
 > The `resize()` method modifies existing shape and array itself.
 
</font>

***

In [15]:
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 20)

thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 20)

thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4, 3)
print(thearray)

[1 2 3 4]
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 0]
 [0 0 0]]


### - **`NumPy Indexing`**
***

In [16]:
array1d

array(['10.8', '2', '1'], dtype='<U11')

In [17]:
array1d[0] # index 5

'10.8'

In [18]:
array1d[0:2] # values in a range

array(['10.8', '2'], dtype='<U11')

### - **`Indexing a 2D array (matrices)`**
***
<font color = #318CE7 size = 3 >
    
The general format is `arr_2d[row][col]` or `arr_2d[row,col]`. I recommend usually using the comma notation for clarity.
 
</font>

***

In [19]:
array2d

array([[1.5, 2.5, 3.5, 4. ],
       [4.5, 5.5, 6.5, 1. ],
       [7.5, 8.5, 9.5, 6. ]])

In [20]:
array2d[0]

array([1.5, 2.5, 3.5, 4. ])

In [21]:
array2d[1][1]

5.5

In [22]:
array2d[2,0] # recommended

7.5

In [23]:
array2d

array([[1.5, 2.5, 3.5, 4. ],
       [4.5, 5.5, 6.5, 1. ],
       [7.5, 8.5, 9.5, 6. ]])

In [24]:
# 2D array slicing
array2d[ : 2 , 1 :  ] 

array([[2.5, 3.5, 4. ],
       [5.5, 6.5, 1. ]])

In [25]:
array2d[: 2 ]

array([[1.5, 2.5, 3.5, 4. ],
       [4.5, 5.5, 6.5, 1. ]])

In [26]:
array2d[1: , 1: ]

array([[5.5, 6.5, 1. ],
       [8.5, 9.5, 6. ]])

### - **`Conditional Selection`**
***


In [27]:
conarr = np.arange(1,11)
conarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
conarr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_conarr = conarr > 4
bool_conarr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
conarr[bool_conarr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
conarr [ conarr > 2 ] = 100
conarr

array([  1,   2, 100, 100, 100, 100, 100, 100, 100, 100])

***

## Stacking: Several arrays can be stacked together along different axes

np.vstack: To stack arrays along vertical axis <br></br>
np.hstack: To stack arrays along horizontal axis <br></br>
np.column_stack: To stack 1-D array as columns into 2-D array <br></br>
np.concatenate: To stack arrays along specified axis (axis is passed as argument) <br></br>

In [32]:
import numpy as np
a = np.array([[1, 2],
             [3, 4]]
            )

b = np.array([[7, 8],
             [9, 10]]
            )


In [33]:
# Vertical Stacking
print(np.vstack((a,b)))

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


In [34]:
# Horizontal Stacking
print(np.hstack((a,b)))

[[ 1  2  7  8]
 [ 3  4  9 10]]


In [35]:
# Stacking Columns
c = [5, 6]
print(np.column_stack((a, c)))

[[1 2 5]
 [3 4 6]]


In [36]:
# Concatenation Method
print(np.concatenate((a,b), axis = 0))

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]


In [37]:
print(np.concatenate((a,b), axis = 1))

[[ 1  2  7  8]
 [ 3  4  9 10]]


## Splitting: Splitting is reverse operation of joining. One array can be split into Several arrays 

np.vsplit: Split array along vertical axis <br></br>
np.hsplit: Split array along horizontal axis <br></br>
np.array_split: Split array along specified axis <br></br>


In [38]:
a = np.array([[1,2,3,4,5,6],
              [0,9,8,7,6,5]]
            )

In [39]:
## Vertical Splitting
print(np.vsplit(a, 2))

[array([[1, 2, 3, 4, 5, 6]]), array([[0, 9, 8, 7, 6, 5]])]


In [40]:
## Horizontal Splitting
print(np.hsplit(a, 2))

[array([[1, 2, 3],
       [0, 9, 8]]), array([[4, 5, 6],
       [7, 6, 5]])]


In [41]:
## Array Split; axis = 0
print(np.array_split(a, 2, axis = 0))

[array([[1, 2, 3, 4, 5, 6]]), array([[0, 9, 8, 7, 6, 5]])]


In [42]:
## Array Split; axis = 1
print(np.array_split(a, 2, axis = 1))

[array([[1, 2, 3],
       [0, 9, 8]]), array([[4, 5, 6],
       [7, 6, 5]])]



### - **` Some Built-in Methods from NumPy Package for creating arrays `**
***
<font color = #318CE7 size = 3 >
    
- `arange` 

- `linspace`

- `random.rand`
 
</font>

***

### np.arange

In [43]:
np.arange(1,101) # 0 .. n-1  (!)`

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [44]:
np.arange(1,101,5) # start, end (exclusive), step

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

___

In [45]:
np.arange(0,   5.1,  0.5) 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

### np.linspace

In [46]:
np.linspace(1,101,5) # evenly space 1d array. 3rd argument is number we want in output

array([  1.,  26.,  51.,  76., 101.])

### np.rand, np.randn, np.randint

In [47]:
# Random Uniform Number Generator
np.random.rand(10)  

array([0.73280734, 0.27838166, 0.59952042, 0.44143619, 0.41388639,
       0.33183349, 0.89820453, 0.8435462 , 0.11115041, 0.70277123])

In [48]:
# Standard Normal Distribution Random Number Generator
snormal = np.random.randn(10000)
print(snormal)
print("mean : ", np.mean(snormal))
print("std. dev.:", np.std(snormal))

[-1.8902345   1.69460199  1.06364304 ... -1.30660919  1.21405254
  0.99224135]
mean :  0.0004975021831563836
std. dev.: 0.9960106951623107


In [49]:
np.random.randint(100, 1000, 5)

array([119, 321, 297, 690, 655])

In [50]:
# Random Integers between Start and End numbers
from numpy.random import randint
randint(1,100)

50

In [51]:
randint(1,100,10)

array([76, 80, 76, 36, 84, 65, 35, 35, 86, 33])

___
<a href='https://www.k2analytics.co.in'> <img src='K2_Logo.jpg' alt="https://k2analytics.co.in" style="width:300px" /></a>